---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: semantic
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
