---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui
  namespace: noconnor-test
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-webui-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name:  open-webui
  namespace: {{ .Release.Namespace }}