---
kind: Service
apiVersion: v1
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: http
  type: ClusterIP
  selector:
    app: litellm

