---
{{- range $key := .Values.proxy_config_files }}
{{- $path := printf "litellm-configs/%s" .name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ regexReplaceAll "_" .name "-" | trimAll ".py" }} 
data:
  {{ .name }}: |
  {{- $.Files.Get $path | nindent 4 -}}
{{- end }}